### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by dereuromark** [phpDocumentor/GraphViz#16]
Can you please release a new version?
We currently have to use dev-master

Thank you!

//cc @mvriel

**Comment by lmanzke** [comment]
:+1:

**Comment by rgex** [comment]
:+1:

**Comment by marius-rizac** [comment]
:+1:

**Comment by ThomasKuehnel** [comment]
:+1:

**Comment by stereomon** [comment]
:+1:

**Comment by nahpeps** [comment]
:+1:

**Comment by mvriel** [comment]
Hello all,

My apologies for the late response; for some reason this request didn't show up on my radar. I have just tagged a new release. Let me know if more action is required.
