### ISSUE TITLE
Add description to composer.json

### ISSUE THREAD

**Issue by metaliciouz** [phpDocumentor/GraphViz#23]
Description required for published packages.

`composer validate` output:
```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
description : The property description is required
```

See this problem in your other package: [#58](https://github.com/phpDocumentor/TypeResolver/issues/58)

**Comment by ashnazg** [comment]
Fixed in 210ff935adb2ad9bc7668f6f551e131891b76c2c.
